"""
ResearchPilot AI — Synthesizer Node
Reads all VFS files from active agents → writes final structured report.
"""
import time
from graph.state import ResearchState
from graph.llm_factory import get_llm
from tools.file_system import vfs_read_all, vfs_read


def synthesizer_node(state: ResearchState) -> dict:
    t0 = time.time()
    query = state["query"]
    vfs = state.get("virtual_files", {})
    active = state.get("active_agents", [])
    retry = state.get("retry_count", 0)
    logs = list(state.get("agent_logs", []))
    timings = dict(state.get("agent_timings", {}))

    logs.append(f"[Synthesizer] Merging all agent outputs into report (attempt {retry + 1})...")

    # Build context from available VFS files
    context_parts = []

    if "research_deep.txt" in vfs:
        context_parts.append(f"## Research Findings\n{vfs['research_deep.txt']}")

    if "statistics.txt" in vfs:
        context_parts.append(f"## Statistical Data\n{vfs['statistics.txt']}")

    if "expert_analysis.txt" in vfs:
        context_parts.append(f"## Domain Expert Analysis\n{vfs['expert_analysis.txt']}")

    if "fact_check.txt" in vfs:
        context_parts.append(f"## Fact Verification\n{vfs['fact_check.txt']}")

    if "references.txt" in vfs:
        context_parts.append(f"## Sources\n{vfs['references.txt']}")

    full_context = "\n\n".join(context_parts)

    retry_instruction = ""
    if retry > 0:
        retry_instruction = "\n\nIMPORTANT: This is a retry. The previous version scored below 7/10. Make it more comprehensive, analytical, and well-structured."

    llm = get_llm(temperature=0.5)

    prompt = f"""You are an expert research writer. Using ALL the provided research data, write a comprehensive, professional research report.

Research Topic: {query}

Research Data:
{full_context[:6000]}

Active agents used: {active}
{retry_instruction}

Write a complete report in this EXACT markdown structure:

# {query}

## Executive Summary
[3-4 sentences: what was researched, key finding, main implication]

## Key Findings
[5-7 specific, evidence-backed findings as bullet points with details]

## Analysis
[400-500 words of in-depth analytical prose connecting the findings]

## Statistical Overview
[Only include if statistics data available — summarise key numbers in context]

## Expert Perspective
[Only include if domain expert data available — 2-3 paragraphs]

## Real-World Examples & Case Studies
[3-5 specific examples with organisations, outcomes, and lessons]

## Challenges & Limitations
[Key obstacles, risks, or caveats — 3-5 points]

## Future Outlook
[Where this is heading — trends, predictions, opportunities]

## Conclusion
[Strong 2-3 sentence synthesis and takeaway]

## References
[List all sources from citations data, numbered]

---
*Report generated by ResearchPilot AI — Autonomous Multi-Agent Research System*
*Agents: {", ".join(active)}*"""

    response = llm.invoke(prompt)
    report = response.content

    timings["synthesizer"] = round(time.time() - t0, 2)
    logs.append("[Synthesizer] Report generated successfully.")

    return {
        "final_report": report,
        "agent_logs": logs,
        "agent_timings": timings,
    }
